//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgeRanger.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using AgeRanger.Data.Models;

  //public partial class SQLiteAgeRangerEntities : DbContext
  //  {
  //      public SQLiteAgeRangerEntities()
  //          : base("name=SQLiteAgeRangerEntities")
  //      {
  //      }
    
  //      protected override void OnModelCreating(DbModelBuilder modelBuilder)
  //      {
  //          throw new UnintentionalCodeFirstException();
  //      }
    
  //      public virtual DbSet<AgeGroup> AgeGroups { get; set; }
  //      public virtual DbSet<Person> People { get; set; }
  //  }
}
